"""initial schema

Revision ID: 045a10723477
Revises: 
Create Date: 2026-06-13 11:38:30.322088

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045a10723477'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_codes',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_sub', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('pkce_challenge_value', sa.String(), nullable=False),
    sa.Column('pkce_challenge_method', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_index(op.f('ix_authorization_codes_client_id'), 'authorization_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_authorization_codes_consumed_at'), 'authorization_codes', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_authorization_codes_expires_at'), 'authorization_codes', ['expires_at'], unique=False)
    op.create_table('clients',
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('secret_hash', sa.LargeBinary(), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.String(), nullable=False),
    sa.Column('allowed_grant_types', sa.String(), nullable=False),
    sa.Column('allowed_scopes', sa.String(), nullable=False),
    sa.Column('redirect_uris', sa.String(), nullable=False),
    sa.Column('default_audience', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_client_id'), 'clients', ['client_id'], unique=False)
    op.create_table('device_codes',
    sa.Column('device_code', sa.String(), nullable=False),
    sa.Column('user_code', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('user_sub', sa.String(), nullable=True),
    sa.Column('denied', sa.Boolean(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_code')
    )
    op.create_index(op.f('ix_device_codes_client_id'), 'device_codes', ['client_id'], unique=False)
    op.create_index(op.f('ix_device_codes_expires_at'), 'device_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_device_codes_user_code'), 'device_codes', ['user_code'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('family_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('user_sub', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('value')
    )
    op.create_index(op.f('ix_refresh_tokens_client_id'), 'refresh_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_consumed_at'), 'refresh_tokens', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('trusted_assertion_issuers',
    sa.Column('issuer', sa.String(), nullable=False),
    sa.Column('public_key_pem', sa.LargeBinary(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('allowed_audiences', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('issuer')
    )
    op.create_table('users',
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sub')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('trusted_assertion_issuers')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_consumed_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_client_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_device_codes_user_code'), table_name='device_codes')
    op.drop_index(op.f('ix_device_codes_expires_at'), table_name='device_codes')
    op.drop_index(op.f('ix_device_codes_client_id'), table_name='device_codes')
    op.drop_table('device_codes')
    op.drop_index(op.f('ix_clients_client_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_authorization_codes_expires_at'), table_name='authorization_codes')
    op.drop_index(op.f('ix_authorization_codes_consumed_at'), table_name='authorization_codes')
    op.drop_index(op.f('ix_authorization_codes_client_id'), table_name='authorization_codes')
    op.drop_table('authorization_codes')
    # ### end Alembic commands ###
